// components/staff/StaffData.js

export const staffData = [
  // ============================================================
  // OFFICE OF THE HEAD OF DEPARTMENT
  // ============================================================
  {
    id: 1,
    initials: "UF",
    firstName: "Ursula Fezeka",
    lastName: "Ngomane",
    fullName: "Ursula Fezeka Ngomane",
    jobTitle: "Executive Assistant",
    componentDescription: "OFFICE OF THE HEAD OF DEPARTMENT",
    programme: "ADMINISTRATION",
    email: "ungomane@ncdedat.gov.za",
    phone: "0725556577",
    location: "Head Office",
    isMentor: false,
    skills: ["Executive Support", "Administration"],
    experience: "6 years"
  },
  {
    id: 2,
    initials: "LL",
    firstName: "Liesl Luane",
    lastName: "Bezuidenhout",
    fullName: "Liesl Luane Bezuidenhout",
    jobTitle: "Assistant Manager: Enterprise Development",
    componentDescription: "OFFICE OF THE HEAD OF DEPARTMENT",
    programme: "ADMINISTRATION",
    email: "lbezuidenhout@ncdedat.gov.za",
    phone: "0829513154",
    location: "Head Office",
    isMentor: false,
    skills: ["Enterprise Development", "Management"],
    experience: "8 years"
  },
  {
    id: 3,
    initials: "LC",
    firstName: "Lizette Cathleen",
    lastName: "Wyngaard",
    fullName: "Lizette Cathleen Wyngaard",
    jobTitle: "Executive Manager: Trade & Sector",
    componentDescription: "OFFICE OF THE HEAD OF DEPARTMENT",
    programme: "ADMINISTRATION",
    email: "lwyngaard2016@gmail.com",
    phone: "0798816854",
    location: "Head Office",
    isMentor: true,
    skills: ["Trade", "Sector Development", "Management"],
    experience: "16 years"
  },
  {
    id: 4,
    initials: "ATM",
    firstName: "Aelred Theophilus Mlungisi",
    lastName: "Mabija",
    fullName: "Aelred Theophilus Mlungisi Mabija",
    jobTitle: "Head of Department (HOD)",
    componentDescription: "OFFICE OF THE HEAD OF DEPARTMENT",
    programme: "ADMINISTRATION",
    email: "tmabija@ncdedat.gov.za",
    phone: "0813744300",
    location: "Head Office",
    isMentor: true,
    skills: ["Leadership", "Strategic Management", "Public Administration"],
    experience: "22 years"
  },

  // ============================================================
  // CHIEF OPERATIONS OFFICER
  // ============================================================
  {
    id: 5,
    initials: "MR",
    firstName: "Mphoentle Rachael",
    lastName: "Musa",
    fullName: "Mphoentle Rachael Musa",
    jobTitle: "Senior Manager: Human Resource Management",
    componentDescription: "CHIEF OPERATIONS OFFICER",
    programme: "ADMINISTRATION",
    email: "mmusa@ncdedat.gov.za",
    phone: "0817877521",
    location: "Head Office",
    isMentor: true,
    skills: ["Human Resources", "Management"],
    experience: "16 years"
  },
  {
    id: 6,
    initials: "TG",
    firstName: "Tebogo Gilbert",
    lastName: "Ngamole",
    fullName: "Tebogo Gilbert Ngamole",
    jobTitle: "Chief Director: Corporate Services",
    componentDescription: "CHIEF OPERATIONS OFFICER",
    programme: "ADMINISTRATION",
    email: "tngamole@ncdedat.gov.za",
    phone: "0836316507",
    location: "Head Office",
    isMentor: true,
    skills: ["Corporate Services", "Leadership"],
    experience: "18 years"
  },

  // ============================================================
  // COMMUNICATION SERVICES
  // ============================================================
  {
    id: 7,
    initials: "PM",
    firstName: "Puseletso Matshidiso",
    lastName: "Phoofolo",
    fullName: "Puseletso Matshidiso Phoofolo",
    jobTitle: "Assistant Manager Communications",
    componentDescription: "COMMUNICATION SERVICES",
    programme: "ADMINISTRATION",
    email: "pphoofolo03@gmail.com",
    phone: "0829660576",
    location: "Head Office",
    isMentor: false,
    skills: ["Communications", "Public Relations"],
    experience: "5 years"
  },
  {
    id: 8,
    initials: "KL",
    firstName: "Kehilwe Lizzie",
    lastName: "Motabogi",
    fullName: "Kehilwe Lizzie Motabogi",
    jobTitle: "Director: Administration Assistant",
    componentDescription: "COMMUNICATION SERVICES",
    programme: "ADMINISTRATION",
    email: "kmotabogi@ncdedat.gov.za",
    phone: "0832747618",
    location: "Head Office",
    isMentor: false,
    skills: ["Communications", "Administration"],
    experience: "6 years"
  },

  // ============================================================
  // HUMAN RESOURCES MANAGEMENT
  // ============================================================
  {
    id: 9,
    initials: "ML",
    firstName: "Michelle Lynn",
    lastName: "Johnson",
    fullName: "Michelle Lynn Johnson",
    jobTitle: "Human Resource Administration Officer",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "johnsonm@ncdedat.gov.za",
    phone: "0732569387",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Administration"],
    experience: "4 years"
  },
  {
    id: 10,
    initials: "LS",
    firstName: "Letshego Shirlyn",
    lastName: "Kwaeng",
    fullName: "Letshego Shirlyn Kwaeng",
    jobTitle: "Human Resource Administration Officer",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "lkwaeng@ncdedat.gov.za",
    phone: "0732619497",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Administration"],
    experience: "4 years"
  },
  {
    id: 11,
    initials: "JM",
    firstName: "Julia Mapule",
    lastName: "Mothibi",
    fullName: "Julia Mapule Mothibi",
    jobTitle: "Human Resource Development Officer",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "mapulemothibi@ncdedat.gov.za",
    phone: "0616223299",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Training", "Development"],
    experience: "7 years"
  },
  {
    id: 12,
    initials: "JN",
    firstName: "Johannes Nicolaas",
    lastName: "Van Zyl",
    fullName: "Johannes Nicolaas Van Zyl",
    jobTitle: "Assistant Manager: Labour Relations",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "jvanzyl@ncdedat.gov.za",
    phone: "0632949468",
    location: "Head Office",
    isMentor: false,
    skills: ["Labour Relations", "Human Resources"],
    experience: "7 years"
  },
  {
    id: 13,
    initials: "R",
    firstName: "Raees",
    lastName: "Toffar",
    fullName: "Raees Toffar",
    jobTitle: "Assistant Manager: Human Resource Administration",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "raees.toffar7@gmail.com",
    phone: "0790779504",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Administration"],
    experience: "6 years"
  },
  {
    id: 14,
    initials: "MS",
    firstName: "Malane Shantel",
    lastName: "Barlow",
    fullName: "Malane Shantel Barlow",
    jobTitle: "Director: Administration Deputy",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "mbarlow@ncdedat.gov.za",
    phone: "0823122465",
    location: "Head Office",
    isMentor: true,
    skills: ["Human Resources", "Management"],
    experience: "10 years"
  },
  {
    id: 15,
    initials: "E",
    firstName: "Elizabeth",
    lastName: "Molefe",
    fullName: "Elizabeth Molefe",
    jobTitle: "Human Resource Development Clerk",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "lmolefe@ncdedat.gov.za",
    phone: "0737360460",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Clerical"],
    experience: "4 years"
  },
  {
    id: 16,
    initials: "NE",
    firstName: "Nthabiseng Elizabeth",
    lastName: "Mmotlana",
    fullName: "Nthabiseng Elizabeth Mmotlana",
    jobTitle: "Organizational Design Practitioner",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "nthabisengmmotlana@gmail.com",
    phone: "0662631698",
    location: "Head Office",
    isMentor: false,
    skills: ["Organisational Design", "Human Resources"],
    experience: "5 years"
  },
  {
    id: 17,
    initials: "K",
    firstName: "Khashifa",
    lastName: "Paulse",
    fullName: "Khashifa Paulse",
    jobTitle: "Human Resource Development Officer",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "khashifapaulse@gmail.com",
    phone: "0824159677",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Training", "Development"],
    experience: "6 years"
  },
  {
    id: 18,
    initials: "J",
    firstName: "Janine",
    lastName: "Krieg",
    fullName: "Janine Krieg",
    jobTitle: "Assistant Director: OD",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "jkrieg@ncdedat.gov.za",
    phone: "0814864211",
    location: "Head Office",
    isMentor: false,
    skills: ["Organisational Development", "Human Resources"],
    experience: "7 years"
  },
  {
    id: 19,
    initials: "MS",
    firstName: "Maude Sarah",
    lastName: "Thomas",
    fullName: "Maude Sarah Thomas",
    jobTitle: "Human Resource Administration Officer",
    componentDescription: "HUMAN RESOURCES MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "mthomas@ncdedat.gov.za",
    phone: "0842503024",
    location: "Head Office",
    isMentor: false,
    skills: ["Human Resources", "Administration"],
    experience: "6 years"
  },

  // ============================================================
  // EQUAL OPPORTUNITIES
  // ============================================================
  {
    id: 20,
    initials: "NC",
    firstName: "Nthabiseng Christina",
    lastName: "Mokgoro",
    fullName: "Nthabiseng Christina Mokgoro",
    jobTitle: "EHWP Clerk",
    componentDescription: "EQUAL OPPORTUNITIES",
    programme: "ADMINISTRATION",
    email: "mokgorochristinanthabiseng@gmail.com",
    phone: "0736434557",
    location: "Head Office",
    isMentor: false,
    skills: ["Employee Wellness", "Clerical"],
    experience: "3 years"
  },
  {
    id: 21,
    initials: "N",
    firstName: "Ntsoaki",
    lastName: "Mereeotlhe",
    fullName: "Ntsoaki Mereeotlhe",
    jobTitle: "Assistant Manager Employee Health Wellness",
    componentDescription: "EQUAL OPPORTUNITIES",
    programme: "ADMINISTRATION",
    email: "nmereeotlhe@ncdedat.gov.za",
    phone: "0823322661",
    location: "Head Office",
    isMentor: false,
    skills: ["Employee Wellness", "Management"],
    experience: "5 years"
  },
  {
    id: 22,
    initials: "MR",
    firstName: "Mokgaetji Rose",
    lastName: "Bomal",
    fullName: "Mokgaetji Rose Bomal",
    jobTitle: "Deputy Director EPWP",
    componentDescription: "EQUAL OPPORTUNITIES",
    programme: "ADMINISTRATION",
    email: "rbomali@ncdedat.gov.za",
    phone: "0661899884",
    location: "Head Office",
    isMentor: true,
    skills: ["EPWP", "Project Management"],
    experience: "11 years"
  },

  // ============================================================
  // CONSUMER ADVISORY SERVICES
  // ============================================================
  {
    id: 23,
    initials: "KL",
    firstName: "Kim Lana",
    lastName: "Sheen",
    fullName: "Kim Lana Sheen",
    jobTitle: "Senior Handels Inspekteur",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "kim81sheen@gmail.com",
    phone: "0736894733",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "4 years"
  },
  {
    id: 24,
    initials: "H",
    firstName: "Hermien",
    lastName: "Lamprecht",
    fullName: "Hermien Lamprecht",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "hermienlamprecht@gmail.com",
    phone: "0820704464",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "5 years"
  },
  {
    id: 25,
    initials: "ZD",
    firstName: "Zelda Delores",
    lastName: "Williams",
    fullName: "Zelda Delores Williams",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "zwilliams@ncdedat.gov.za",
    phone: "0737045741",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "5 years"
  },
  {
    id: 26,
    initials: "BA",
    firstName: "Boitumelo Arnold",
    lastName: "Lukang",
    fullName: "Boitumelo Arnold Lukang",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "balukang@ncdedat.gov.za",
    phone: "0725800724",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "4 years"
  },
  {
    id: 27,
    initials: "MT",
    firstName: "Marsha Terri-Lee",
    lastName: "Jason-Madibane",
    fullName: "Marsha Terri-Lee Jason-Madibane",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "marshajason1987@gmail.com",
    phone: "0611282517",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "6 years"
  },
  {
    id: 28,
    initials: "K",
    firstName: "Kenneth",
    lastName: "Henderson",
    fullName: "Kenneth Henderson",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "khenderson@ncdedat.gov.za",
    phone: "0605890427",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "7 years"
  },
  {
    id: 29,
    initials: "M",
    firstName: "Marina",
    lastName: "Pelser",
    fullName: "Marina Pelser",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "pelsermarina@yahoo.com",
    phone: "0793114524",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "5 years"
  },
  {
    id: 30,
    initials: "LY",
    firstName: "Linda Yonela",
    lastName: "Filifana",
    fullName: "Linda Yonela Filifana",
    jobTitle: "Consumer Inspector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "lindafilifana@gmail.com",
    phone: "0712198848",
    location: "Head Office",
    isMentor: false,
    skills: ["Consumer Protection", "Inspection"],
    experience: "4 years"
  },
  {
    id: 31,
    initials: "JR",
    firstName: "Jon Relph",
    lastName: "Speek",
    fullName: "Jon Relph Speek",
    jobTitle: "Manager: Consumer Protector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "relphspeek@gmail.com",
    phone: "0768128672",
    location: "Head Office",
    isMentor: true,
    skills: ["Consumer Protection", "Management"],
    experience: "12 years"
  },
  {
    id: 32,
    initials: "DP",
    firstName: "Daniel Prins",
    lastName: "Olivier",
    fullName: "Daniel Prins Olivier",
    jobTitle: "Manager: Consumer Protector",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "polivier@ncdedat.gov.za",
    phone: "0828125617",
    location: "Head Office",
    isMentor: true,
    skills: ["Consumer Protection", "Management", "Legal"],
    experience: "16 years"
  },
  {
    id: 33,
    initials: "MWS",
    firstName: "Mario Waldo Shane",
    lastName: "Williams",
    fullName: "Mario Waldo Shane Williams",
    jobTitle: "Legal Administration Officer",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "mariowilliams297@gmail.com",
    phone: "0681518318",
    location: "Head Office",
    isMentor: false,
    skills: ["Legal", "Administration"],
    experience: "5 years"
  },
  {
    id: 34,
    initials: "M",
    firstName: "Melissa",
    lastName: "Ramasamy",
    fullName: "Melissa Ramasamy",
    jobTitle: "Senior Legal Admin Officer",
    componentDescription: "CONSUMER ADVISORY SERVICES",
    programme: "BUSINESS REGULATION & GOVERNANCE",
    email: "jsraluminium@mweb.co.za",
    phone: "0620396392",
    location: "Head Office",
    isMentor: false,
    skills: ["Legal", "Administration"],
    experience: "7 years"
  },

  // ============================================================
  // ECONOMIC PLANNING
  // ============================================================
  {
    id: 35,
    initials: "M",
    firstName: "Marcele",
    lastName: "Van Der Lith",
    fullName: "Marcele Van Der Lith",
    jobTitle: "Administrative Officer: Administration",
    componentDescription: "ECONOMIC PLANNING",
    programme: "ECONOMIC PLANNING",
    email: "mvanderlith@ncdedat.gov.za",
    phone: "0712138558",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration"],
    experience: "5 years"
  },
  {
    id: 36,
    initials: "GS",
    firstName: "Gopane Samuel",
    lastName: "Mabilo",
    fullName: "Gopane Samuel Mabilo",
    jobTitle: "Executive Manager: Trade & Sector",
    componentDescription: "ECONOMIC PLANNING",
    programme: "ECONOMIC PLANNING",
    email: "smabilo@ncdedat.gov.za",
    phone: "0695388752",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Planning", "Management", "Trade"],
    experience: "17 years"
  },

  // ============================================================
  // STRATEGY MANAGEMENT
  // ============================================================
  {
    id: 37,
    initials: "LJ",
    firstName: "Letlhogonolo John",
    lastName: "Setlhabi",
    fullName: "Letlhogonolo John Setlhabi",
    jobTitle: "Director: Administration Deputy",
    componentDescription: "STRATEGY MANAGEMENT",
    programme: "ECONOMIC PLANNING",
    email: "lsetlhabi@ncdedat.gov.za",
    phone: "0833668175",
    location: "Head Office",
    isMentor: true,
    skills: ["Administration", "Management", "Strategy"],
    experience: "10 years"
  },
  {
    id: 38,
    initials: "LM",
    firstName: "Luvuyo Manqoba",
    lastName: "Mabena",
    fullName: "Luvuyo Manqoba Mabena",
    jobTitle: "Assistant Manager: Policy and Planning",
    componentDescription: "STRATEGY MANAGEMENT",
    programme: "ECONOMIC PLANNING",
    email: "lvuyot@gmail.com",
    phone: "0794483224",
    location: "Head Office",
    isMentor: false,
    skills: ["Policy", "Planning", "Administration"],
    experience: "4 years"
  },
  {
    id: 39,
    initials: "KV",
    firstName: "Keneilwe Valerie",
    lastName: "Nkosi",
    fullName: "Keneilwe Valerie Nkosi",
    jobTitle: "Director",
    componentDescription: "STRATEGY MANAGEMENT",
    programme: "ECONOMIC PLANNING",
    email: "kenkosi74@gmail.com",
    phone: "0822652232",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Development", "Policy", "Management"],
    experience: "14 years"
  },

  // ============================================================
  // MACRO AND MICRO ECONOMIC RESEARCH
  // ============================================================
  {
    id: 40,
    initials: "CN",
    firstName: "Colette Nicole",
    lastName: "Wax",
    fullName: "Colette Nicole Wax",
    jobTitle: "Assistant Manager: Micro & Macro Economic Research",
    componentDescription: "MACRO AND MICRO ECONOMIC RESEARCH",
    programme: "ECONOMIC PLANNING",
    email: "cwax@ncdedat.gov.za",
    phone: "0828738465",
    location: "Head Office",
    isMentor: false,
    skills: ["Economics", "Research", "Macroeconomics", "Microeconomics"],
    experience: "6 years"
  },
  {
    id: 41,
    initials: "R",
    firstName: "Reratile",
    lastName: "Mathibe",
    fullName: "Reratile Mathibe",
    jobTitle: "Manager: Economic Research & Policy Development",
    componentDescription: "MACRO AND MICRO ECONOMIC RESEARCH",
    programme: "ECONOMIC PLANNING",
    email: "reratile@icloud.com",
    phone: "0723680644",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Research", "Policy Development", "Analysis"],
    experience: "13 years"
  },

  // ============================================================
  // STRATEGIC INITIATIVES
  // ============================================================
  {
    id: 42,
    initials: "NU",
    firstName: "Nongqele Ursula",
    lastName: "Mpeluza",
    fullName: "Nongqele Ursula Mpeluza",
    jobTitle: "Secretary",
    componentDescription: "STRATEGIC INITIATIVES",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "umpeluza@ncdedat.gov.za",
    phone: "0733877059",
    location: "Head Office",
    isMentor: false,
    skills: ["Secretarial", "Administration"],
    experience: "5 years"
  },

  // ============================================================
  // KNOWLEDGE MANAGEMENT
  // ============================================================
  {
    id: 43,
    initials: "N",
    firstName: "Nadia",
    lastName: "Paulse",
    fullName: "Nadia Paulse",
    jobTitle: "Secretary",
    componentDescription: "KNOWLEDGE MANAGEMENT",
    programme: "ECONOMIC PLANNING",
    email: "npaulse@ncdedat.gov.za",
    phone: "0711301181",
    location: "Head Office",
    isMentor: false,
    skills: ["Secretarial", "Administration"],
    experience: "4 years"
  },
  {
    id: 44,
    initials: "RV",
    firstName: "Rodwyn Vern",
    lastName: "Grewan",
    fullName: "Rodwyn Vern Grewan",
    jobTitle: "Senior Manager: Knowledge Management",
    componentDescription: "KNOWLEDGE MANAGEMENT",
    programme: "ECONOMIC PLANNING",
    email: "rgrewan@ncdedat.gov.za",
    phone: "0684361536",
    location: "Head Office",
    isMentor: true,
    skills: ["Knowledge Management", "Innovation", "Strategy"],
    experience: "11 years"
  },

  // ============================================================
  // MANAGEM INFO SYS & ENTERR INFO ARCHITECTURE
  // ============================================================
  {
    id: 45,
    initials: "W",
    firstName: "Winston",
    lastName: "Rooiland",
    fullName: "Winston Rooiland",
    jobTitle: "Manager: Enterprise Information Architecture",
    componentDescription: "MANAGEM INFO SYS & ENTERR INFO ARCHITECTURE",
    programme: "ECONOMIC PLANNING",
    email: "wrooiland@ncdedat.gov.za",
    phone: "0795631146",
    location: "Head Office",
    isMentor: true,
    skills: ["Information Systems", "Enterprise Architecture", "IT Management"],
    experience: "13 years"
  },
  {
    id: 46,
    initials: "MF",
    firstName: "Mohau Fred",
    lastName: "Girruite",
    fullName: "Mohau Fred Girruite",
    jobTitle: "Administrative Officer",
    componentDescription: "MANAGEM INFO SYS & ENTERR INFO ARCHITECTURE",
    programme: "ECONOMIC PLANNING",
    email: "mfgirruite@gmail.com",
    phone: "0768627214",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "IT Support"],
    experience: "5 years"
  },
  {
    id: 47,
    initials: "VEG",
    firstName: "Vernon Erwin Garnett",
    lastName: "Van Nel",
    fullName: "Vernon Erwin Garnett Van Nel",
    jobTitle: "Director: Administration Assistant",
    componentDescription: "MANAGEM INFO SYS & ENTERR INFO ARCHITECTURE",
    programme: "ECONOMIC PLANNING",
    email: "vvannel@ncdedat.gov.za",
    phone: "0837373702",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "IT Management"],
    experience: "8 years"
  },

  // ============================================================
  // INTEGRATED ECONOMIC DEVELOPMENT SERVICES
  // ============================================================
  {
    id: 48,
    initials: "MM",
    firstName: "Michelle Mathilda",
    lastName: "Smith",
    fullName: "Michelle Mathilda Smith",
    jobTitle: "Administrative Officer",
    componentDescription: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "smithm@ncdedat.gov.za",
    phone: "0828345764",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration"],
    experience: "5 years"
  },
  {
    id: 49,
    initials: "KD",
    firstName: "Kevin Daryll",
    lastName: "Christians",
    fullName: "Kevin Daryll Christians",
    jobTitle: "Executive Manager: IEDS",
    componentDescription: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "dchristians@ncdedat.gov.za",
    phone: "0798888822",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Development", "Management"],
    experience: "16 years"
  },

  // ============================================================
  // DISTRICT SERVICE CENTRES
  // ============================================================
  {
    id: 50,
    initials: "DM",
    firstName: "Desmond Mhlangabezi",
    lastName: "Maganga",
    fullName: "Desmond Mhlangabezi Maganga",
    jobTitle: "Assistant Manager: LED District Coordinator",
    componentDescription: "DISTRICT SERVICE CENTRES",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "maganga20@gmail.com",
    phone: "0723834882",
    location: "District Office",
    isMentor: false,
    skills: ["Local Economic Development", "Coordination"],
    experience: "7 years"
  },

  // ============================================================
  // ENTERPRISE DEVELOPMENT
  // ============================================================
  {
    id: 51,
    initials: "MP",
    firstName: "Modiagkotla Percival",
    lastName: "Mokubung",
    fullName: "Modiagkotla Percival Mokubung",
    jobTitle: "Manager: Economic Sector Research",
    componentDescription: "ENTERPRISE DEVELOPMENT",
    programme: "ADMINISTRATION",
    email: "pmokubung@ncdedat.gov.za",
    phone: "0823098908",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Research", "Sector Development"],
    experience: "10 years"
  },

  // ============================================================
  // ECONOMIC TRANSFORMATION AND EMPOWERMENT
  // ============================================================
  {
    id: 52,
    initials: "EM",
    firstName: "Estelle Marlene",
    lastName: "Dennis",
    fullName: "Estelle Marlene Dennis",
    jobTitle: "Administrative Officer: Transformation & Empowerment",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "edennis@ncdedat.gov.za",
    phone: "0670939758",
    location: "Head Office",
    isMentor: false,
    skills: ["Economic Transformation", "Empowerment", "Administration"],
    experience: "7 years"
  },
  {
    id: 53,
    initials: "BN",
    firstName: "Bryan Neil",
    lastName: "Damoense",
    fullName: "Bryan Neil Damoense",
    jobTitle: "Administrative Officer",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "bdamoense@ncdedat.gov.za",
    phone: "0839266330",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Economic Development"],
    experience: "5 years"
  },
  {
    id: 54,
    initials: "GT",
    firstName: "Galaletsang Tsholofelo",
    lastName: "Motlhale",
    fullName: "Galaletsang Tsholofelo Motlhale",
    jobTitle: "Administrative Officer",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "tgmodisane1234@gmail.com",
    phone: "0732002183",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration"],
    experience: "3 years"
  },
  {
    id: 55,
    initials: "R",
    firstName: "Refilwe",
    lastName: "Dungu",
    fullName: "Refilwe Dungu",
    jobTitle: "Administrative Officer",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "rdungu@ncdedat.gov.za",
    phone: "0814962063",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration"],
    experience: "3 years"
  },
  {
    id: 56,
    initials: "GU",
    firstName: "Goitsemang Ursula",
    lastName: "Motsage",
    fullName: "Goitsemang Ursula Motsage",
    jobTitle: "Administrative Officer: Transformation & Empowerment",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "ursulamotsage@gmail.com",
    phone: "0746342235",
    location: "Head Office",
    isMentor: false,
    skills: ["Economic Transformation", "Empowerment", "Administration"],
    experience: "4 years"
  },
  {
    id: 57,
    initials: "TJ",
    firstName: "Tiisetso Joseph",
    lastName: "Taolo",
    fullName: "Tiisetso Joseph Taolo",
    jobTitle: "Assistant Manager: Enterprise Development",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "tiisetso.taolo@gmail.com",
    phone: "0713572714",
    location: "Head Office",
    isMentor: false,
    skills: ["Enterprise Development", "Management"],
    experience: "6 years"
  },
  {
    id: 58,
    initials: "KD",
    firstName: "Kopela Daniel",
    lastName: "Mohohlo",
    fullName: "Kopela Daniel Mohohlo",
    jobTitle: "Deputy Director: BBBEE",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "dmohohlo@ncdedat.gov.za",
    phone: "0763524235",
    location: "Head Office",
    isMentor: true,
    skills: ["BBBEE", "Economic Empowerment"],
    experience: "10 years"
  },
  {
    id: 59,
    initials: "AS",
    firstName: "Agnes Seyanokeng",
    lastName: "Ntidisa",
    fullName: "Agnes Seyanokeng Ntidisa",
    jobTitle: "Senior Manager: Economic Empowerment",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "sntidisa@gmail.com",
    phone: "0716751787",
    location: "Head Office",
    isMentor: true,
    skills: ["Economic Empowerment", "Management"],
    experience: "12 years"
  },
  {
    id: 60,
    initials: "JK",
    firstName: "Judy Kedibonye",
    lastName: "Moalekwa",
    fullName: "Judy Kedibonye Moalekwa",
    jobTitle: "Assistant Manager: Transformation & Empowerment",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "jmoalekwa@ncdedat.gov.za",
    phone: "0714314621",
    location: "Head Office",
    isMentor: false,
    skills: ["Transformation", "Empowerment", "Management"],
    experience: "6 years"
  },
  {
    id: 61,
    initials: "TNG",
    firstName: "Terence Neo Gift",
    lastName: "Bosman",
    fullName: "Terence Neo Gift Bosman",
    jobTitle: "Assistant Manager: LED District Coordinator",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "gbosman73@gmail.com",
    phone: "0714103413",
    location: "District Office",
    isMentor: false,
    skills: ["Local Economic Development", "Coordination"],
    experience: "6 years"
  },
  {
    id: 62,
    initials: "Y",
    firstName: "Yoliswa",
    lastName: "Lekhoathi",
    fullName: "Yoliswa Lekhoathi",
    jobTitle: "Director: Administration Deputy",
    componentDescription: "ECONOMIC TRANSFORMATION AND EMPOWERMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "ylekhoathi@gmail.com",
    phone: "0829259120",
    location: "Head Office",
    isMentor: true,
    skills: ["Administration", "Management"],
    experience: "12 years"
  },

  // ============================================================
  // TRADE AND INVESTMENT
  // ============================================================
  {
    id: 63,
    initials: "MJ",
    firstName: "Motlalepula Jessica",
    lastName: "Makgetla",
    fullName: "Motlalepula Jessica Makgetla",
    jobTitle: "Assistant Manager: Trade & Investment",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "makgetlajessica@gmail.com",
    phone: "0795563752",
    location: "Head Office",
    isMentor: false,
    skills: ["Trade", "Investment", "Management"],
    experience: "6 years"
  },
  {
    id: 64,
    initials: "L",
    firstName: "Lizette",
    lastName: "Van Der Walt-Cronje",
    fullName: "Lizette Van Der Walt-Cronje",
    jobTitle: "Assistant Manager: Trade & Investment",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "lvanderwalt@ncdedat.gov.za",
    phone: "0828907559",
    location: "Head Office",
    isMentor: false,
    skills: ["Trade", "Investment", "Management"],
    experience: "7 years"
  },
  {
    id: 65,
    initials: "DO",
    firstName: "Darius Olehil",
    lastName: "Babuseng",
    fullName: "Darius Olehil Babuseng",
    jobTitle: "Director: Trade and Investment",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "dbabuseng@gmail.com",
    phone: "0760507575",
    location: "Head Office",
    isMentor: true,
    skills: ["Trade", "Investment", "Strategy"],
    experience: "15 years"
  },
  {
    id: 66,
    initials: "RJ",
    firstName: "Riaan Jacobus",
    lastName: "Warie",
    fullName: "Riaan Jacobus Warie",
    jobTitle: "Chief Director: Trade and Sector Development",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "rwarie@ncdedat.gov.za",
    phone: "0798772828",
    location: "Head Office",
    isMentor: true,
    skills: ["Trade", "Sector Development", "Leadership"],
    experience: "18 years"
  },
  {
    id: 67,
    initials: "G",
    firstName: "Godfrey",
    lastName: "Seipone",
    fullName: "Godfrey Seipone",
    jobTitle: "Deputy Director: Alternative Energy (Engineering)",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "godfreyseipone@gmail.com",
    phone: "0723455101",
    location: "Head Office",
    isMentor: true,
    skills: ["Alternative Energy", "Engineering", "Renewable Energy"],
    experience: "8 years"
  },
  {
    id: 68,
    initials: "NC",
    firstName: "Napo Calvin",
    lastName: "Ramabina",
    fullName: "Napo Calvin Ramabina",
    jobTitle: "Deputy Director: Alternative Energy (Economist)",
    componentDescription: "TRADE AND INVESTMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "nramabina@gmail.com",
    phone: "0718821511",
    location: "Head Office",
    isMentor: true,
    skills: ["Alternative Energy", "Economics", "Renewable Energy"],
    experience: "10 years"
  },

  // ============================================================
  // DEPARTMENTAL ACCOUNTING
  // ============================================================
  {
    id: 69,
    initials: "JL",
    firstName: "Janine Liesel",
    lastName: "Haai",
    fullName: "Janine Liesel Haai",
    jobTitle: "Personal Assistant",
    componentDescription: "DEPARTMENTAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "jhaai@ncdedat.gov.za",
    phone: "",
    location: "Head Office",
    isMentor: false,
    skills: ["Personal Assistance", "Administration"],
    experience: "6 years"
  },

  // ============================================================
  // MANAGEMENT ACCOUNTING
  // ============================================================
  {
    id: 70,
    initials: "TM",
    firstName: "Thebe Mpho",
    lastName: "Raboi",
    fullName: "Thebe Mpho Raboi",
    jobTitle: "Manager: Departmental Accounting",
    componentDescription: "MANAGEMENT ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "raboikanyothebe@gmail.com",
    phone: "0732684946",
    location: "Head Office",
    isMentor: true,
    skills: ["Management Accounting", "Finance"],
    experience: "11 years"
  },
  {
    id: 71,
    initials: "NN",
    firstName: "Nikita Natasha",
    lastName: "Speranza",
    fullName: "Nikita Natasha Speranza",
    jobTitle: "Assistant Manager: Management Accounting",
    componentDescription: "MANAGEMENT ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "ayedeehdee@gmail.com",
    phone: "0727700175",
    location: "Head Office",
    isMentor: false,
    skills: ["Management Accounting", "Finance"],
    experience: "5 years"
  },
  {
    id: 72,
    initials: "SMAE",
    firstName: "Susara Martha Alletta Elizabeth",
    lastName: "Swartz",
    fullName: "Susara Martha Alletta Elizabeth Swartz",
    jobTitle: "Assistant Manager: Management Accounting",
    componentDescription: "MANAGEMENT ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "sswartz@ncdedat.gov.za",
    phone: "0835477424",
    location: "Head Office",
    isMentor: true,
    skills: ["Management Accounting", "Finance"],
    experience: "9 years"
  },
  {
    id: 73,
    initials: "FN",
    firstName: "Frans Nicolaas",
    lastName: "Booysen",
    fullName: "Frans Nicolaas Booysen",
    jobTitle: "Director: Management Accounting",
    componentDescription: "MANAGEMENT ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "fbooysen@ncdedat.gov.za",
    phone: "0718830658",
    location: "Head Office",
    isMentor: true,
    skills: ["Management Accounting", "Finance", "Leadership"],
    experience: "18 years"
  },

  // ============================================================
  // FINANCIAL ACCOUNTING
  // ============================================================
  {
    id: 74,
    initials: "KA",
    firstName: "Kegomoditswe Angela",
    lastName: "Letebele",
    fullName: "Kegomoditswe Angela Letebele",
    jobTitle: "Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "kegomoditsweletebele@gmail.com",
    phone: "0762776242",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "6 years"
  },
  {
    id: 75,
    initials: "SE",
    firstName: "Solomon Edmund",
    lastName: "Moalekwa",
    fullName: "Solomon Edmund Moalekwa",
    jobTitle: "Accounting Clerk",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "solmoalekwa@gmail.com",
    phone: "0639237198",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Clerical"],
    experience: "5 years"
  },
  {
    id: 76,
    initials: "NF",
    firstName: "Ntlafatso Faith",
    lastName: "Otswelwang",
    fullName: "Ntlafatso Faith Otswelwang",
    jobTitle: "Accounting Clerk",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "ntlafifotswelwang@gmail.com",
    phone: "0676830817",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Clerical"],
    experience: "3 years"
  },
  {
    id: 77,
    initials: "KG",
    firstName: "Kgomotso Gwendoline",
    lastName: "Mothibi",
    fullName: "Kgomotso Gwendoline Mothibi",
    jobTitle: "State Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "kgmothibi79@gmail.com",
    phone: "0829054219",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "5 years"
  },
  {
    id: 78,
    initials: "KS",
    firstName: "Kollie Sophia",
    lastName: "Mazimba",
    fullName: "Kollie Sophia Mazimba",
    jobTitle: "Ass Manager",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "ksmazimba@ncdedat.gov.za",
    phone: "0697752497",
    location: "Head Office",
    isMentor: true,
    skills: ["Financial Accounting", "Management"],
    experience: "15 years"
  },
  {
    id: 79,
    initials: "MI",
    firstName: "Matsheleng Innocentia",
    lastName: "Gooiman",
    fullName: "Matsheleng Innocentia Gooiman",
    jobTitle: "Director: Departmental Accounting",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "mgooiman@ncdedat.gov.za",
    phone: "0833467730",
    location: "Head Office",
    isMentor: true,
    skills: ["Accounting", "Finance", "Leadership"],
    experience: "16 years"
  },
  {
    id: 80,
    initials: "Z",
    firstName: "Zahid",
    lastName: "Cader",
    fullName: "Zahid Cader",
    jobTitle: "Chief Financial Officer",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "zcader@ncdedat.gov.za",
    phone: "0670121049",
    location: "Head Office",
    isMentor: true,
    skills: ["Finance", "Leadership", "Accounting"],
    experience: "20 years"
  },
  {
    id: 81,
    initials: "GL",
    firstName: "George Lebogang",
    lastName: "Pienaar",
    fullName: "George Lebogang Pienaar",
    jobTitle: "State Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "lebogangpie@gmail.com",
    phone: "0677475766",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "4 years"
  },
  {
    id: 82,
    initials: "ST",
    firstName: "Sylvia Tshepisho",
    lastName: "Chotetsi",
    fullName: "Sylvia Tshepisho Chotetsi",
    jobTitle: "State Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "tchotetsi@ncdedat.gov.za",
    phone: "0731169919",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "9 years"
  },
  {
    id: 83,
    initials: "N",
    firstName: "Nicole",
    lastName: "Naude",
    fullName: "Nicole Naude",
    jobTitle: "State Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "nauden@ncdedat.gov.za",
    phone: "0764998595",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "4 years"
  },
  {
    id: 84,
    initials: "PG",
    firstName: "Phumza Grace",
    lastName: "Nodom",
    fullName: "Phumza Grace Nodom",
    jobTitle: "State Accountant",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "phumzanodom61@gmail.com",
    phone: "0829260180",
    location: "Head Office",
    isMentor: false,
    skills: ["Accounting", "Finance"],
    experience: "5 years"
  },
  {
    id: 85,
    initials: "PL",
    firstName: "Patience Lesego",
    lastName: "Radebe",
    fullName: "Patience Lesego Radebe",
    jobTitle: "Ass Manager",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "lesego219@gmail.com",
    phone: "0797808750",
    location: "Head Office",
    isMentor: true,
    skills: ["Accounting", "Management"],
    experience: "9 years"
  },
  {
    id: 86,
    initials: "BC",
    firstName: "Bradley Craig",
    lastName: "Starr",
    fullName: "Bradley Craig Starr",
    jobTitle: "Ass Manager",
    componentDescription: "FINANCIAL ACCOUNTING",
    programme: "ADMINISTRATION",
    email: "bstarr@ncdedat.gov.za",
    phone: "0605640689",
    location: "Head Office",
    isMentor: false,
    skills: ["Management", "Administration"],
    experience: "6 years"
  },

  // ============================================================
  // SUPPLY CHAIN MANAGEMENT
  // ============================================================
  {
    id: 87,
    initials: "MV",
    firstName: "Malebogo Veronica",
    lastName: "Windwaai",
    fullName: "Malebogo Veronica Windwaai",
    jobTitle: "Accounting Clerk: Procurement",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "malebogowindwaai@gmail.com",
    phone: "0630896615",
    location: "Head Office",
    isMentor: false,
    skills: ["Procurement", "Accounting", "Clerical"],
    experience: "4 years"
  },
  {
    id: 88,
    initials: "GN",
    firstName: "Geraldine Nthabiseng",
    lastName: "Mmetseng",
    fullName: "Geraldine Nthabiseng Mmetseng",
    jobTitle: "Accounting Clerk: Procurement",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "n.mmetseng@gmail.com",
    phone: "0604377190",
    location: "Head Office",
    isMentor: false,
    skills: ["Procurement", "Accounting", "Clerical"],
    experience: "4 years"
  },
  {
    id: 89,
    initials: "PB",
    firstName: "Petunia Bokamoso",
    lastName: "Mbuli",
    fullName: "Petunia Bokamoso Mbuli",
    jobTitle: "Supply Chain Management Clerk",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "pertuniambuli@ncdedat.gov.za",
    phone: "0711305640",
    location: "Head Office",
    isMentor: false,
    skills: ["Supply Chain", "Clerical"],
    experience: "3 years"
  },
  {
    id: 90,
    initials: "A",
    firstName: "Asanda",
    lastName: "Williams",
    fullName: "Asanda Williams",
    jobTitle: "Supply Chain Management Clerk",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "awilliams@ncdedat.gov.za",
    phone: "0789522591",
    location: "Head Office",
    isMentor: false,
    skills: ["Supply Chain", "Clerical"],
    experience: "3 years"
  },
  {
    id: 91,
    initials: "BB",
    firstName: "Bassanio Baffour",
    lastName: "Awuah",
    fullName: "Bassanio Baffour Awuah",
    jobTitle: "Director: Administration Assistant",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "bassanioa@ncdedat.gov.za",
    phone: "0671435355",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Supply Chain"],
    experience: "8 years"
  },
  {
    id: 92,
    initials: "AT",
    firstName: "Alocius Tshwaro",
    lastName: "Toto",
    fullName: "Alocius Tshwaro Toto",
    jobTitle: "Assistant Manager: Supply Chain Management",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "tshwarot90@gmail.com",
    phone: "0817624164",
    location: "Head Office",
    isMentor: false,
    skills: ["Supply Chain", "Management"],
    experience: "5 years"
  },
  {
    id: 93,
    initials: "NP",
    firstName: "Nozipho Primrose",
    lastName: "Magawu",
    fullName: "Nozipho Primrose Magawu",
    jobTitle: "Deputy Director: Supply Chain Management",
    componentDescription: "SUPPLY CHAIN MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "nozipho.magawu@gmail.com",
    phone: "0834622318",
    location: "Head Office",
    isMentor: true,
    skills: ["Supply Chain", "Procurement", "Management"],
    experience: "12 years"
  },

  // ============================================================
  // PROCUREMENT
  // ============================================================
  {
    id: 94,
    initials: "NG",
    firstName: "Nomsa Grace",
    lastName: "Ncube",
    fullName: "Nomsa Grace Ncube",
    jobTitle: "Administrative Officer: Procurement",
    componentDescription: "PROCUREMENT",
    programme: "ADMINISTRATION",
    email: "nomsa.srgear@gmail.com",
    phone: "0761409897",
    location: "Head Office",
    isMentor: false,
    skills: ["Procurement", "Administration"],
    experience: "5 years"
  },
  {
    id: 95,
    initials: "LD",
    firstName: "Lorato Dabea",
    lastName: "Mashishi",
    fullName: "Lorato Dabea Mashishi",
    jobTitle: "Senior Administrative Officer: Procurement",
    componentDescription: "PROCUREMENT",
    programme: "ADMINISTRATION",
    email: "lmashishi@ncdedat.gov.za",
    phone: "0726389231",
    location: "Head Office",
    isMentor: false,
    skills: ["Procurement", "Administration"],
    experience: "6 years"
  },

  // ============================================================
  // ASSET MANAGEMENT
  // ============================================================
  {
    id: 96,
    initials: "LP",
    firstName: "Lesego Portia",
    lastName: "Seekoei",
    fullName: "Lesego Portia Seekoei",
    jobTitle: "Asset Management Clerk",
    componentDescription: "ASSET MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "lesegoportiaseekoei@gmail.com",
    phone: "0717507867",
    location: "Head Office",
    isMentor: false,
    skills: ["Asset Management", "Clerical"],
    experience: "3 years"
  },
  {
    id: 97,
    initials: "L",
    firstName: "Leroy",
    lastName: "Crowie",
    fullName: "Leroy Crowie",
    jobTitle: "Supervisory Clerk",
    componentDescription: "ASSET MANAGEMENT",
    programme: "ADMINISTRATION",
    email: "lcrowie@ncdedat.gov.za",
    phone: "0716489980",
    location: "Head Office",
    isMentor: false,
    skills: ["Asset Management", "Supervisory"],
    experience: "4 years"
  },

  // ============================================================
  // TRANSPORT
  // ============================================================
  {
    id: 98,
    initials: "A",
    firstName: "Abel",
    lastName: "McGuire",
    fullName: "Abel McGuire",
    jobTitle: "Transport Officer",
    componentDescription: "TRANSPORT",
    programme: "ADMINISTRATION",
    email: "amcguire@ncdedat.gov.za",
    phone: "0693964244",
    location: "Head Office",
    isMentor: false,
    skills: ["Transport", "Logistics"],
    experience: "7 years"
  },

  // ============================================================
  // CORPORATE SERVICES
  // ============================================================
  {
    id: 99,
    initials: "PG",
    firstName: "Praise Galaletsang",
    lastName: "Ledibane",
    fullName: "Praise Galaletsang Ledibane",
    jobTitle: "Receptionist",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "pledibane@ncdedat.gov.za",
    phone: "0838961800",
    location: "Head Office",
    isMentor: false,
    skills: ["Reception", "Customer Service"],
    experience: "3 years"
  },
  {
    id: 100,
    initials: "VS",
    firstName: "Virginia Sindiswa",
    lastName: "Tsholo",
    fullName: "Virginia Sindiswa Tsholo",
    jobTitle: "Intern",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "sindiswatsholo35@gmail.com",
    phone: "0783001220",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Learning"],
    experience: "1 year"
  },
  {
    id: 101,
    initials: "LP",
    firstName: "Letlhogonolo Prudence",
    lastName: "Badukanye",
    fullName: "Letlhogonolo Prudence Badukanye",
    jobTitle: "Intern",
    componentDescription: "CORPORATE SERVICES",
    programme: "ECONOMIC PLANNING",
    email: "letlhogonolo.badukanye@gmail.com",
    phone: "0713040013",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Learning"],
    experience: "1 year"
  },
  {
    id: 102,
    initials: "G",
    firstName: "Gaodirelwe",
    lastName: "Bokkies",
    fullName: "Gaodirelwe Bokkies",
    jobTitle: "Intern",
    componentDescription: "CORPORATE SERVICES",
    programme: "ECONOMIC PLANNING",
    email: "bokkiesmathews@gmail.com",
    phone: "0781551802",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Learning"],
    experience: "1 year"
  },
  {
    id: 103,
    initials: "MA",
    firstName: "Motlalepula Annacleta",
    lastName: "Namate",
    fullName: "Motlalepula Annacleta Namate",
    jobTitle: "Senior Administration Clerk",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "mnamate@ncdedat.gov.za",
    phone: "0785658837",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Clerical"],
    experience: "3 years"
  },
  {
    id: 104,
    initials: "GK",
    firstName: "Gloria Kgalalelo",
    lastName: "Swartz",
    fullName: "Gloria Kgalalelo Swartz",
    jobTitle: "Assistant Manager: Legal Services",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "glrswartz@yahoo.co.uk",
    phone: "0735174034",
    location: "Head Office",
    isMentor: false,
    skills: ["Legal", "Management"],
    experience: "7 years"
  },
  {
    id: 105,
    initials: "R",
    firstName: "Reshanthan",
    lastName: "Moodley",
    fullName: "Reshanthan Moodley",
    jobTitle: "Assistant Manager: Hardware & Software Support",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "rmoodley20@gmail.com",
    phone: "0842693294",
    location: "Head Office",
    isMentor: false,
    skills: ["IT", "Hardware", "Software Support"],
    experience: "7 years"
  },
  {
    id: 106,
    initials: "L",
    firstName: "Lucky",
    lastName: "Vezi",
    fullName: "Lucky Vezi",
    jobTitle: "Deputy Director: Legal and Labour Relations",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "lvezi@ncdedat.gov.za",
    phone: "0634686389",
    location: "Head Office",
    isMentor: true,
    skills: ["Legal", "Labour Relations", "Management"],
    experience: "10 years"
  },
  {
    id: 107,
    initials: "TC",
    firstName: "Thandiwe Catherine",
    lastName: "Modibela",
    fullName: "Thandiwe Catherine Modibela",
    jobTitle: "Senior Manager: Corporate Services",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "tmodibela@ncdedat.gov.za",
    phone: "",
    location: "Head Office",
    isMentor: true,
    skills: ["Corporate Services", "Management"],
    experience: "14 years"
  },
  {
    id: 108,
    initials: "LI",
    firstName: "Lebogang Ivan",
    lastName: "Gontse",
    fullName: "Lebogang Ivan Gontse",
    jobTitle: "Administrative Officer",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "lgontse@ncdedat.gov.za",
    phone: "0832226731",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "IT"],
    experience: "8 years"
  },
  {
    id: 109,
    initials: "GJ",
    firstName: "Geuvan Jonathan",
    lastName: "Boltman",
    fullName: "Geuvan Jonathan Boltman",
    jobTitle: "Desktop Support Technician",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "gboltman@ncdedat.gov.za",
    phone: "0827887514",
    location: "Head Office",
    isMentor: false,
    skills: ["IT Support", "Desktop Support"],
    experience: "7 years"
  },
  {
    id: 110,
    initials: "KM",
    firstName: "Keotshepile Mavis",
    lastName: "Mokgalagadi",
    fullName: "Keotshepile Mavis Mokgalagadi",
    jobTitle: "Desktop Support Technician",
    componentDescription: "CORPORATE SERVICES",
    programme: "ADMINISTRATION",
    email: "kmokgalagadi@ncdedat.gov.za",
    phone: "0810867609",
    location: "Head Office",
    isMentor: false,
    skills: ["IT Support", "Desktop Support"],
    experience: "4 years"
  },

  // ============================================================
  // REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT
  // ============================================================
  {
    id: 111,
    initials: "S",
    firstName: "Shereen",
    lastName: "Herholdt",
    fullName: "Shereen Herholdt",
    jobTitle: "Project Administrative Officer",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "shakes2128@gmail.com",
    phone: "0767356128",
    location: "District Office",
    isMentor: false,
    skills: ["Project Administration"],
    experience: "5 years"
  },
  {
    id: 112,
    initials: "HC",
    firstName: "Hendrik Christoffel",
    lastName: "Louw",
    fullName: "Hendrik Christoffel Louw",
    jobTitle: "Senior Manager: Rural and LED & EPWP",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "hlouw416@gmail.com",
    phone: "0813232533",
    location: "Head Office",
    isMentor: true,
    skills: ["Local Economic Development", "EPWP", "Management"],
    experience: "14 years"
  },
  {
    id: 113,
    initials: "PC",
    firstName: "Palesa Charity",
    lastName: "Mocwane",
    fullName: "Palesa Charity Mocwane",
    jobTitle: "Assistant Manager: LED District Coordinator",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "palesamoc@yahoo.com",
    phone: "0762494459",
    location: "District Office",
    isMentor: false,
    skills: ["Local Economic Development", "Coordination"],
    experience: "4 years"
  },
  {
    id: 114,
    initials: "TH",
    firstName: "Thapelo Harry",
    lastName: "Modumo",
    fullName: "Thapelo Harry Modumo",
    jobTitle: "Assistant Manager: EPWP",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "tpmodumo@gmail.com",
    phone: "0676070592",
    location: "District Office",
    isMentor: false,
    skills: ["EPWP", "Management"],
    experience: "5 years"
  },
  {
    id: 115,
    initials: "VM",
    firstName: "Vinolia Makgomo",
    lastName: "Mafotja",
    fullName: "Vinolia Makgomo Mafotja",
    jobTitle: "Assistant Manager: EPWP",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "mahlatse.dedatepwp@gmail.com",
    phone: "0676453028",
    location: "Head Office",
    isMentor: false,
    skills: ["EPWP", "Management"],
    experience: "10 years"
  },
  {
    id: 116,
    initials: "K",
    firstName: "Kitsiso",
    lastName: "Mamapula",
    fullName: "Kitsiso Mamapula",
    jobTitle: "Assistant Manager: LED District Coordinator",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "kmamapula@ncdedat.gov.za",
    phone: "0825759933",
    location: "District Office",
    isMentor: false,
    skills: ["Local Economic Development", "Coordination"],
    experience: "5 years"
  },
  {
    id: 117,
    initials: "MM",
    firstName: "Michael Modisakgotla",
    lastName: "Moseki",
    fullName: "Michael Modisakgotla Moseki",
    jobTitle: "Deputy Director: Mining & Mineral Beneficiation",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "mmoseki@ncdedat.gov.za",
    phone: "",
    location: "Head Office",
    isMentor: true,
    skills: ["Mining", "Mineral Beneficiation"],
    experience: "11 years"
  },
  {
    id: 118,
    initials: "S",
    firstName: "Sithembiso",
    lastName: "Mtanga",
    fullName: "Sithembiso Mtanga",
    jobTitle: "Deputy Director: Mining & Mineral Beneficiation",
    componentDescription: "REGIONAL AND LOCAL ENTERPRISE DEVELOPMENT",
    programme: "INTEGRATED ECONOMIC DEVELOPMENT SERVICES",
    email: "sithembisomtanga@gmail.com",
    phone: "0731737894",
    location: "Head Office",
    isMentor: true,
    skills: ["Mining", "Mineral Beneficiation"],
    experience: "9 years"
  },

  // ============================================================
  // SECTOR DEVELOPMENT
  // ============================================================
  {
    id: 119,
    initials: "C",
    firstName: "Cabanga",
    lastName: "Moyo",
    fullName: "Cabanga Moyo",
    jobTitle: "Senior Manager: Sector Development",
    componentDescription: "SECTOR DEVELOPMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "moyoc@ncdedat.gov.za",
    phone: "0835794072",
    location: "Head Office",
    isMentor: true,
    skills: ["Sector Development", "Management"],
    experience: "13 years"
  },
  {
    id: 120,
    initials: "YK",
    firstName: "Yanda Kendall",
    lastName: "Gqabaza",
    fullName: "Yanda Kendall Gqabaza",
    jobTitle: "Senior Manager: Policy & Planning",
    componentDescription: "SECTOR DEVELOPMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "gqabaza@gmail.com",
    phone: "0695327036",
    location: "Head Office",
    isMentor: true,
    skills: ["Policy", "Planning", "Sector Development"],
    experience: "13 years"
  },
  {
    id: 121,
    initials: "CC",
    firstName: "Chantel Charmaine",
    lastName: "Harrison",
    fullName: "Chantel Charmaine Harrison",
    jobTitle: "Secretary",
    componentDescription: "SECTOR DEVELOPMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "charrison@ncdedat.gov.za",
    phone: "0799318532",
    location: "Head Office",
    isMentor: false,
    skills: ["Secretarial", "Administration"],
    experience: "4 years"
  },
  {
    id: 122,
    initials: "MB",
    firstName: "Modirapula Bernard",
    lastName: "Mabele",
    fullName: "Modirapula Bernard Mabele",
    jobTitle: "Manager: Sector Development",
    componentDescription: "SECTOR DEVELOPMENT",
    programme: "TRADE AND SECTOR DEVELOPMENT",
    email: "bernard.mabele2011@gmail.com",
    phone: "0725538334",
    location: "Head Office",
    isMentor: true,
    skills: ["Sector Development", "Management"],
    experience: "15 years"
  },

  // ============================================================
  // SENIOR MANAGER - TOURISM
  // ============================================================
  {
    id: 123,
    initials: "N",
    firstName: "Nadia",
    lastName: "Miller",
    fullName: "Nadia Miller",
    jobTitle: "Secretary",
    componentDescription: "SENIOR MANAGER - TOURISM",
    programme: "TOURISM",
    email: "nmiller@ncdedat.gov.za",
    phone: "0848224066",
    location: "Head Office",
    isMentor: false,
    skills: ["Secretarial", "Administration"],
    experience: "4 years"
  },
  {
    id: 124,
    initials: "JE",
    firstName: "Jean Elizabeth",
    lastName: "Wilson",
    fullName: "Jean Elizabeth Wilson",
    jobTitle: "Executive Manager: Tourism",
    componentDescription: "SENIOR MANAGER - TOURISM",
    programme: "TOURISM",
    email: "jeanwilson014@gmail.com",
    phone: "0832558807",
    location: "Head Office",
    isMentor: true,
    skills: ["Tourism", "Management", "Strategy"],
    experience: "15 years"
  },
  {
    id: 125,
    initials: "C",
    firstName: "Christelle",
    lastName: "Du Plessis",
    fullName: "Christelle Du Plessis",
    jobTitle: "Tourism Officer: Tourism Planning",
    componentDescription: "SENIOR MANAGER - TOURISM",
    programme: "TOURISM",
    email: "cduplessis@ncdedat.gov.za",
    phone: "0824588315",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning"],
    experience: "5 years"
  },

  // ============================================================
  // SUB DIRECTORATE - TOURISM PLANNING
  // ============================================================
  {
    id: 126,
    initials: "VS",
    firstName: "Vincent Silvester",
    lastName: "Cupido",
    fullName: "Vincent Silvester Cupido",
    jobTitle: "Manager: Tourism Development & Training",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "vincent.dtec@gmail.com",
    phone: "0664844484",
    location: "Head Office",
    isMentor: true,
    skills: ["Tourism Development", "Training", "Management"],
    experience: "12 years"
  },
  {
    id: 127,
    initials: "MS",
    firstName: "Mason Sipho",
    lastName: "Mampe",
    fullName: "Mason Sipho Mampe",
    jobTitle: "Senior Manager: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "smampe14@gmail.com",
    phone: "0824140295",
    location: "Head Office",
    isMentor: true,
    skills: ["Tourism", "Planning", "Management"],
    experience: "14 years"
  },
  {
    id: 128,
    initials: "RJ",
    firstName: "Reneilwe Jeannett",
    lastName: "Mokabeng",
    fullName: "Reneilwe Jeannett Mokabeng",
    jobTitle: "Tourism Officer",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "rmokabeng@ncdedat.gov.za",
    phone: "0742374336",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism"],
    experience: "3 years"
  },
  {
    id: 129,
    initials: "H",
    firstName: "Heinrich",
    lastName: "Mapanka",
    fullName: "Heinrich Mapanka",
    jobTitle: "Tourism Officer: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "heinrich.dtec@gmail.com",
    phone: "0620871224",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning"],
    experience: "4 years"
  },
  {
    id: 130,
    initials: "T",
    firstName: "Thapelo",
    lastName: "Khatwane",
    fullName: "Thapelo Khatwane",
    jobTitle: "Tourism Officer: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "tkhatwane@ncdedat.gov.za",
    phone: "",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning"],
    experience: "3 years"
  },
  {
    id: 131,
    initials: "VJ",
    firstName: "Vuyokazi Joy",
    lastName: "Duze",
    fullName: "Vuyokazi Joy Duze",
    jobTitle: "Tourism Officer: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "vuyokaziduze717@gmail.com",
    phone: "0788603710",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning"],
    experience: "3 years"
  },
  {
    id: 132,
    initials: "MK",
    firstName: "Millicent Kedibone",
    lastName: "Thabane",
    fullName: "Millicent Kedibone Thabane",
    jobTitle: "Tourism Officer: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "millicentthabane@yahoo.com",
    phone: "0714206561",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning"],
    experience: "3 years"
  },
  {
    id: 133,
    initials: "N",
    firstName: "Nasiphi",
    lastName: "Banya",
    fullName: "Nasiphi Banya",
    jobTitle: "Tourism Officer",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "nbanya@ncdedat.gov.za",
    phone: "0839660469",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism"],
    experience: "5 years"
  },
  {
    id: 134,
    initials: "AM",
    firstName: "Andile Mathews",
    lastName: "Mlawu",
    fullName: "Andile Mathews Mlawu",
    jobTitle: "Assistant Manager: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "amlawu@ncdedat.gov.za",
    phone: "0789321862",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning", "Management"],
    experience: "6 years"
  },
  {
    id: 135,
    initials: "AM",
    firstName: "Andries Mosimanegape",
    lastName: "Mokgele",
    fullName: "Andries Mosimanegape Mokgele",
    jobTitle: "Assistant Manager: Tourism Planning",
    componentDescription: "SUB DIRECTORATE - TOURISM PLANNING",
    programme: "TOURISM",
    email: "pmokgele71@yahoo.com",
    phone: "0846897251",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Planning", "Management"],
    experience: "5 years"
  },

  // ============================================================
  // SUB DIRE - PERTNERSIP ENTER & DESTINATION DEV
  // ============================================================
  {
    id: 136,
    initials: "JL",
    firstName: "Johannes Lodiwikus",
    lastName: "Van Schalkwyk",
    fullName: "Johannes Lodiwikus Van Schalkwyk",
    jobTitle: "Senior Manager: Tourism",
    componentDescription: "SUB DIRE - PERTNERSIP ENTER & DESTINATION DEV",
    programme: "TOURISM",
    email: "jvs.dtec@gmail.com",
    phone: "0833244652",
    location: "Head Office",
    isMentor: true,
    skills: ["Tourism", "Partnerships", "Destination Development"],
    experience: "14 years"
  },

  // ============================================================
  // DIVISION - TOURISM BUSINESS PROMOTION
  // ============================================================
  {
    id: 137,
    initials: "SL",
    firstName: "Segomotso Lornah",
    lastName: "Galehole",
    fullName: "Segomotso Lornah Galehole",
    jobTitle: "Tourism Officer: Business Promotion",
    componentDescription: "DIVISION - TOURISM BUSINESS PROMOTION",
    programme: "TOURISM",
    email: "sgalehole@ncdedat.gov.za",
    phone: "0822698277",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Business Promotion"],
    experience: "4 years"
  },
  {
    id: 138,
    initials: "CJ",
    firstName: "Carlyn Janelle",
    lastName: "Smit",
    fullName: "Carlyn Janelle Smit",
    jobTitle: "Tourism Officer: Business Promotion",
    componentDescription: "DIVISION - TOURISM BUSINESS PROMOTION",
    programme: "TOURISM",
    email: "csmit@ncdedat.gov.za",
    phone: "0832802120",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Business Promotion"],
    experience: "4 years"
  },
  {
    id: 139,
    initials: "LJ",
    firstName: "Luchelle Josephine",
    lastName: "Van Neel",
    fullName: "Luchelle Josephine Van Neel",
    jobTitle: "Assistant Manager: Partnership Ent Destination Dev",
    componentDescription: "DIVISION - TOURISM BUSINESS PROMOTION",
    programme: "TOURISM",
    email: "lvanneel@ncdedat.gov.za",
    phone: "0825524454",
    location: "Head Office",
    isMentor: false,
    skills: ["Tourism", "Partnerships", "Destination Development"],
    experience: "5 years"
  },

  // ============================================================
  // EXECUTIVE SUPPORT
  // ============================================================
  {
    id: 140,
    initials: "MG",
    firstName: "Moeti Gilbert",
    lastName: "Maibi",
    fullName: "Moeti Gilbert Maibi",
    jobTitle: "Director: Administration Deputy",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mmaibi@ncdedat.gov.za",
    phone: "0822187798",
    location: "Head Office",
    isMentor: true,
    skills: ["Administration", "Management", "Monitoring"],
    experience: "11 years"
  },
  {
    id: 141,
    initials: "TB",
    firstName: "Tebogo Basil",
    lastName: "Gaborone",
    fullName: "Tebogo Basil Gaborone",
    jobTitle: "Director",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "basilgaborone@gmail.com",
    phone: "0663003979",
    location: "Head Office",
    isMentor: true,
    skills: ["Governance", "Risk Management", "Leadership"],
    experience: "14 years"
  },
  {
    id: 142,
    initials: "H",
    firstName: "Horatious",
    lastName: "Bergman",
    fullName: "Horatious Bergman",
    jobTitle: "Messenger/Driver",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "hbergman@ncdedat.gov.za",
    phone: "",
    location: "Head Office",
    isMentor: false,
    skills: ["Messenger", "Driver", "Logistics"],
    experience: "12 years"
  },
  {
    id: 143,
    initials: "EP",
    firstName: "Edward Phemelo",
    lastName: "Leburu",
    fullName: "Edward Phemelo Leburu",
    jobTitle: "Security Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "pphemelo700@gmail.com",
    phone: "0714228547",
    location: "Head Office",
    isMentor: false,
    skills: ["Security"],
    experience: "5 years"
  },
  {
    id: 144,
    initials: "PM",
    firstName: "Paulinah Mantsatsi",
    lastName: "Molebedi",
    fullName: "Paulinah Mantsatsi Molebedi",
    jobTitle: "Security Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mmolebedi@ncdedat.gov.za",
    phone: "0798124612",
    location: "Head Office",
    isMentor: false,
    skills: ["Security"],
    experience: "5 years"
  },
  {
    id: 145,
    initials: "BB",
    firstName: "Buthata Brian",
    lastName: "Tsamaise",
    fullName: "Buthata Brian Tsamaise",
    jobTitle: "Security Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "btsamaise@ncdedat.gov.za",
    phone: "0745739626",
    location: "Head Office",
    isMentor: false,
    skills: ["Security"],
    experience: "4 years"
  },
  {
    id: 146,
    initials: "DN",
    firstName: "Deborah Nisha",
    lastName: "Van Wyk",
    fullName: "Deborah Nisha Van Wyk",
    jobTitle: "Security Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "deborahvanwyk@ncdedat.gov.za",
    phone: "0817493549",
    location: "Head Office",
    isMentor: false,
    skills: ["Security"],
    experience: "4 years"
  },
  {
    id: 147,
    initials: "KV",
    firstName: "Kelebamang Violet",
    lastName: "Kadise",
    fullName: "Kelebamang Violet Kadise",
    jobTitle: "Security Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "kkadise@ncdedat.gov.za",
    phone: "0710512642",
    location: "Head Office",
    isMentor: false,
    skills: ["Security"],
    experience: "8 years"
  },
  {
    id: 148,
    initials: "JL",
    firstName: "Jeremy Lindsay",
    lastName: "Martin",
    fullName: "Jeremy Lindsay Martin",
    jobTitle: "Messenger/Driver",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "jmartin@ncdedat.gov.za",
    phone: "0729170121",
    location: "Head Office",
    isMentor: false,
    skills: ["Messenger", "Driver", "Logistics"],
    experience: "8 years"
  },
  {
    id: 149,
    initials: "RT",
    firstName: "Rosy Tombi",
    lastName: "Lang",
    fullName: "Rosy Tombi Lang",
    jobTitle: "Switchboard Operator",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mothibik@ncdedat.gov.za",
    phone: "0732605746",
    location: "Head Office",
    isMentor: false,
    skills: ["Customer Service", "Switchboard"],
    experience: "6 years"
  },
  {
    id: 150,
    initials: "KD",
    firstName: "Kagisho David",
    lastName: "Mokubung",
    fullName: "Kagisho David Mokubung",
    jobTitle: "Senior Registry Clerk",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mokubungk@ncdedat.gov.za",
    phone: "0788459141",
    location: "Head Office",
    isMentor: false,
    skills: ["Records Management", "Clerical"],
    experience: "4 years"
  },
  {
    id: 151,
    initials: "IM",
    firstName: "Ikeleng Margaret",
    lastName: "Mohulatsi",
    fullName: "Ikeleng Margaret Mohulatsi",
    jobTitle: "Registry Clerk",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mmohulatsi@ncdedat.gov.za",
    phone: "0646289364",
    location: "Head Office",
    isMentor: false,
    skills: ["Records Management", "Clerical"],
    experience: "6 years"
  },
  {
    id: 152,
    initials: "BK",
    firstName: "Boitumelo Keren-Happuch",
    lastName: "Mothibi",
    fullName: "Boitumelo Keren-Happuch Mothibi",
    jobTitle: "Administrative Officer",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "mothibib@ncdedat.gov.za",
    phone: "0764563095",
    location: "Head Office",
    isMentor: false,
    skills: ["Administration", "Governance"],
    experience: "4 years"
  },
  {
    id: 153,
    initials: "SD",
    firstName: "Sian Darlene",
    lastName: "Pophaim",
    fullName: "Sian Darlene Pophaim",
    jobTitle: "Assistant Manager: Governance",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "spophaim@ncdedat.gov.za",
    phone: "0825119927",
    location: "Head Office",
    isMentor: false,
    skills: ["Governance", "Management"],
    experience: "6 years"
  },
  {
    id: 154,
    initials: "TH",
    firstName: "Thabo Haward",
    lastName: "Lichaba",
    fullName: "Thabo Haward Lichaba",
    jobTitle: "Assistant Manager: Risk Management",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "thlichaba.1987@gmail.com",
    phone: "0736794813",
    location: "Head Office",
    isMentor: false,
    skills: ["Risk Management", "Management"],
    experience: "8 years"
  },
  {
    id: 155,
    initials: "SC",
    firstName: "Sameul Collin",
    lastName: "Nel",
    fullName: "Sameul Collin Nel",
    jobTitle: "Assistant Director Strategy Management",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "collin.upt@gmail.com",
    phone: "0647688268",
    location: "Head Office",
    isMentor: false,
    skills: ["Strategic Management", "Planning"],
    experience: "8 years"
  },
  {
    id: 156,
    initials: "TW",
    firstName: "Tyrone Wesley",
    lastName: "Palm",
    fullName: "Tyrone Wesley Palm",
    jobTitle: "Deputy Director: Strategic Management & Evaluation",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "tpalm@ncdedat.gov.za",
    phone: "0829274562",
    location: "Head Office",
    isMentor: false,
    skills: ["Strategic Management", "Monitoring", "Evaluation"],
    experience: "7 years"
  },
  {
    id: 157,
    initials: "GM",
    firstName: "Gloria Masego",
    lastName: "Tlhalogang",
    fullName: "Gloria Masego Tlhalogang",
    jobTitle: "Records Manager",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ECONOMIC PLANNING",
    email: "mtlhalogang@ncdedat.gov.za",
    phone: "0827445128",
    location: "Head Office",
    isMentor: false,
    skills: ["Records Management"],
    experience: "7 years"
  },
  {
    id: 158,
    initials: "Z",
    firstName: "Zoleka",
    lastName: "Mbin",
    fullName: "Zoleka Mbin",
    jobTitle: "Director Strategic Management Monitoring & Evaluation",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "zolekambinda@gmail.com",
    phone: "0823807745",
    location: "Head Office",
    isMentor: true,
    skills: ["Strategic Management", "Monitoring", "Evaluation"],
    experience: "12 years"
  },
  {
    id: 159,
    initials: "RT",
    firstName: "Roberto Theodore",
    lastName: "Moses",
    fullName: "Roberto Theodore Moses",
    jobTitle: "Director: Administration Deputy",
    componentDescription: "EXECUTIVE SUPPORT",
    programme: "ADMINISTRATION",
    email: "rmoses@ncdedat.gov.za",
    phone: "0822288225",
    location: "Head Office",
    isMentor: true,
    skills: ["Administration", "Research", "Information Management"],
    experience: "12 years"
  }
];